export { Dashboard } from './Dashboard/Dashboard';
export { Library } from './Library/Library';
export { Settings } from './Settings/Settings';
export { Profile } from './Profile/Profile';
export { Catalog } from './Catalog/Catalog';
export { Achievements } from './Achievements/Achievements';
export { GameDetails } from './GameDetails/GameDetails';
export { Downloads } from './Downloads/Downloads';
export { Astra } from './Astra/Astra';
